[project]
name = "library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ulf Jährig", email = "ulf.jaehrig@tipico.com" }
]
requires-python = ">=3.13"
dependencies = [
    "icalendar>=6.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
